//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace offers.itacademy.ge.Application.Exceptions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("offers.itacademy.ge.Application.Exceptions.Resources.AppExceptionMessages", typeof(AppExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation window in 5 minute, it is expired.
        /// </summary>
        internal static string CancellationWindowExpired {
            get {
                return ResourceManager.GetString("CancellationWindowExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category with this specifications already exists.
        /// </summary>
        internal static string CategoryAlreadyExists {
            get {
                return ResourceManager.GetString("CategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category with this specifications is not found.
        /// </summary>
        internal static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company is already activated.
        /// </summary>
        internal static string CompanyAlreadyActivated {
            get {
                return ResourceManager.GetString("CompanyAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company is not activated yet.
        /// </summary>
        internal static string CompanyNotActivated {
            get {
                return ResourceManager.GetString("CompanyNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company with this specifications was not fund.
        /// </summary>
        internal static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        internal static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cancell purchase.
        /// </summary>
        internal static string FailedToCancelPurchase {
            get {
                return ResourceManager.GetString("FailedToCancelPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to complete purchase.
        /// </summary>
        internal static string FailedToCompletePurchase {
            get {
                return ResourceManager.GetString("FailedToCompletePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file size exceeds limit, allowed size is 5 MB.
        /// </summary>
        internal static string FileSizeLimitViolation {
            get {
                return ResourceManager.GetString("FileSizeLimitViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image upload failed die to system error.
        /// </summary>
        internal static string ImageUploadException {
            get {
                return ResourceManager.GetString("ImageUploadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient company balance for refund.
        /// </summary>
        internal static string InsufficientCompanyBalance {
            get {
                return ResourceManager.GetString("InsufficientCompanyBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  your balance is not enough to cover purchase expenses.
        /// </summary>
        internal static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough goods in stock.
        /// </summary>
        internal static string InsufficientStocks {
            get {
                return ResourceManager.GetString("InsufficientStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file.
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format.
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some users are missing for refunding.
        /// </summary>
        internal static string InvalidPurchaseState {
            get {
                return ResourceManager.GetString("InvalidPurchaseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user type.
        /// </summary>
        internal static string InvalidUserType {
            get {
                return ResourceManager.GetString("InvalidUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer is already cancelled.
        /// </summary>
        internal static string OfferAlreadyCancelled {
            get {
                return ResourceManager.GetString("OfferAlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer is not valid.
        /// </summary>
        internal static string OfferisNotActiveAnymore {
            get {
                return ResourceManager.GetString("OfferisNotActiveAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer is not active at the moment.
        /// </summary>
        internal static string OfferNotActive {
            get {
                return ResourceManager.GetString("OfferNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer is not cancellable.
        /// </summary>
        internal static string OfferNotCancellable {
            get {
                return ResourceManager.GetString("OfferNotCancellable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer not found.
        /// </summary>
        internal static string OfferNotFound {
            get {
                return ResourceManager.GetString("OfferNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size and page number must be positive.
        /// </summary>
        internal static string PageNumberOrPageSizeMustBePositive {
            get {
                return ResourceManager.GetString("PageNumberOrPageSizeMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produck lacks essential details about itself and company.
        /// </summary>
        internal static string ProductMissesEssentialDetails {
            get {
                return ResourceManager.GetString("ProductMissesEssentialDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product was not found with this specifications.
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase is not active anymore.
        /// </summary>
        internal static string PurchaseNotActive {
            get {
                return ResourceManager.GetString("PurchaseNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase not found.
        /// </summary>
        internal static string PurchaseNotFound {
            get {
                return ResourceManager.GetString("PurchaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        internal static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized user to access this offer.
        /// </summary>
        internal static string UnauthorizedOfferAccess {
            get {
                return ResourceManager.GetString("UnauthorizedOfferAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is unauthorized to modify given product.
        /// </summary>
        internal static string UnauthorizedOfferModification {
            get {
                return ResourceManager.GetString("UnauthorizedOfferModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this username already exists.
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string UserOrPasswordNotValid {
            get {
                return ResourceManager.GetString("UserOrPasswordNotValid", resourceCulture);
            }
        }
    }
}
