//------------------------------------------------------------------------------
// <auto-generated>
//     This Code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the Code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace offers.itacademy.ge.Application.Validations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("offers.itacademy.ge.Application.Validations.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance is required.
        /// </summary>
        internal static string BalanceIsRequired {
            get {
                return ResourceManager.GetString("BalanceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requesting balance can not be negative.
        /// </summary>
        internal static string BalanceIsRequiredCanNotBeNegative {
            get {
                return ResourceManager.GetString("BalanceIsRequiredCanNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category id is required.
        /// </summary>
        internal static string CategoryIdRequired {
            get {
                return ResourceManager.GetString("CategoryIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is required.
        /// </summary>
        internal static string CategoryNameEmpty {
            get {
                return ResourceManager.GetString("CategoryNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company id is required.
        /// </summary>
        internal static string CompanyIdRequired {
            get {
                return ResourceManager.GetString("CompanyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password confirmation is required.
        /// </summary>
        internal static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        internal static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration time must be greater than current utc time plus one hour.
        /// </summary>
        internal static string ExpirationTimeGreaterThanUtcNowPlusOneHour {
            get {
                return ResourceManager.GetString("ExpirationTimeGreaterThanUtcNowPlusOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration time is required.
        /// </summary>
        internal static string ExpirationTimerequired {
            get {
                return ResourceManager.GetString("ExpirationTimerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File length must be more than 0.
        /// </summary>
        internal static string FileCanNotBeEmpty {
            get {
                return ResourceManager.GetString("FileCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required.
        /// </summary>
        internal static string FileIsRequired {
            get {
                return ResourceManager.GetString("FileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size is : .
        /// </summary>
        internal static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name field can not be more than 100 characters.
        /// </summary>
        internal static string MaximumLengthForCategoryName {
            get {
                return ResourceManager.GetString("MaximumLengthForCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description can not be more than 500 characters.
        /// </summary>
        internal static string MaximumLengthForDescription {
            get {
                return ResourceManager.GetString("MaximumLengthForDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be more than 100 characters.
        /// </summary>
        internal static string MaximumLengthForName {
            get {
                return ResourceManager.GetString("MaximumLengthForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can not be more than 100 characters.
        /// </summary>
        internal static string MaximumLengthForPassword {
            get {
                return ResourceManager.GetString("MaximumLengthForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username field  can not be more than 50 characters.
        /// </summary>
        internal static string MaximumLengthForUserName {
            get {
                return ResourceManager.GetString("MaximumLengthForUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be minimum 6 characters.
        /// </summary>
        internal static string MinimumpasswordLengts {
            get {
                return ResourceManager.GetString("MinimumpasswordLengts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only following types are allowed.
        /// </summary>
        internal static string OnlyFollowingAllowedTypes {
            get {
                return ResourceManager.GetString("OnlyFollowingAllowedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price must be greater that or equal to 0.
        /// </summary>
        internal static string PriceGreaterThanOrEqualZero {
            get {
                return ResourceManager.GetString("PriceGreaterThanOrEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is required.
        /// </summary>
        internal static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity must be greater than or equal to 0.
        /// </summary>
        internal static string QuantityGreaterThanOrEqualZero {
            get {
                return ResourceManager.GetString("QuantityGreaterThanOrEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is required.
        /// </summary>
        internal static string QuantityRequired {
            get {
                return ResourceManager.GetString("QuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        internal static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
    }
}
